apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xn23a1l0e-python
  janus-idp.io/tekton: xn23a1l0e-python
  backstage.io/kubernetes-id: xn23a1l0e-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xn23a1l0e-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
