apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xn23a1l0e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xn23a1l0e-python 
  name: xn23a1l0e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xn23a1l0e-python 
